baseURL = "https://pdps-taipei-100th.netlify.app/"
title = "臺北市平等國小百周年校慶專屬網站"

defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false

[outputs]
  section = ["HTML", "JSON"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
category = "categories"

