# default config
baseurl = "https://pdps-taipei.netlify.app"
languageCode = "en-us"
title = "臺北市平等國小百周年校慶專屬網站"
# theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
# google analytics
googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"



# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "臺北市平等國小百周年紀念網站"
# Preloader
preloader = true
# search
search = true
# about author
author = "Li Chi-Haw"
author_image = "images/banner-img.png"
bio = ""
# Contact info
time = "日期：110年6月6日"
date = "時間：上午9時30分至14時"
mobile = "電話：(02)2861-0503"
mobile2 = "傳真：(02)2861-3642"
email = "電子郵件：pdps@pdps.tp.edu.tw"
address = "活動地址：臺北市士林區平菁街101號"
donate1 = "[捐款意向書](/images/uploads/donate/donate-1.docx)"
donate2 = "[捐款收支管理委員會作業要點](/images/uploads/donate/donate-2.docx)"
invitation1 = "[邀請卡封面](/images/uploads/invitation/invitation-01.png)"
invitation2 = "[邀請卡內頁](/images/uploads/invitation/invitation-02.png)"
# Contact Form Action
contact_form_action = "#"
# copyright
copyright = "網站建置於民國110年5月1日__網頁維護者：黎季昊__網頁主題：[themefisher.com](themefisher.com)"

# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = "https://facebook.com/themefisher"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-linkedin"
link = "#"

[[params.social]]
icon = "ti-github"
link = "#"