[[main]]
identifier = "about"
name = "About"
url = "/en/about/"
weight = 10

[[main]]
identifier = "history"
name = "History"
url = "/en/about/history/"
parent = "about"
weight = 20

[[main]]
identifier = "activity"
name = "Activity"
url = "/en/about/activity/"
parent = "about"
weight = 30

[[main]]
identifier = "faculty"
name = "Faculty"
url = "/en/about/faculty/"
parent = "about"
weight = 40

[[main]]
identifier = "place"
name = "Exhibition Venue"
url = "/en/about/place"
parent = "about"
weight = 50

[[main]]
identifier = "collect_music"
name = "NTHU Chamber Ensemble"
url = "/en/collect/music/"
parent = "about"
weight = 60

[[main]]
identifier = "collect_art"
name = "NTHU Art Salon"
url = "/en/collect/art/"
parent = "about"
weight = 70




[[main]]
identifier = "programs"
name = "Programs"
url = "/en/exhibitions/"
weight = 100

[[main]]
identifier = "public_art"
name = "Public Art"
url = "/en/exhibitions/"
weight = 110
parent = "programs"

[[main]]
identifier = "visual_art"
name = "Visual Art"
url = "/en/exhibitions/"
weight = 120
parent = "programs"

[[main]]
identifier = "performing_art"
name = "Performing Art"
url = "/en/exhibitions/"
weight = 130
parent = "programs"

[[main]]
identifier = "film_art"
name = "Film Art"
url = "/en/exhibitions/"
weight = 140
parent = "programs"

[[main]]
identifier = "publication"
name = "Publications"
url = "/en/publications/"
weight = 200

[[main]]
identifier = "friends"
name = "Friends"
url = "/en/friends/"
weight = 210

[[main]]
identifier = "calendar"
name = "Calendar"
url = "/en/calendar/"
weight = 220
